title: Commitments and Resources
description: Progress needs commitments and accountability. These are mine.
theme: just-the-docs

url: https://neurorishika.github.io/commitments
logo: "nrcommitment.png"

aux_links:
  About Me: https://neurorishika.github.io

aux_links_new_tab: true  
  
