title: Neurorishika's Resources
description: Progress needs commitments and accountability. These are mine.
theme: just-the-docs

url: https://neurorishika.github.io/resources
logo: "assets/images/logo.png"

aux_links:
  About Me: https://neurorishika.github.io

aux_links_new_tab: true  

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 Rishika Mohanta. Distributed by an <a href=\"https://github.com/neurorishika/resources/tree/main/LICENSE.txt\">MIT license.</a>"

ga_tracking: G-CL1QH1RXW6
ga_tracking_anonymize_ip: true